import pandas as pd
import os
from typing import List, Dict, Any

def read_index_fields_from_csv() -> Dict[str, Any]:
    """
    Read index fields from CSV files generated by field_maker.py
    Returns the same structure as the original get_index_fields() function
    """
    # The fields directory is at src/utils/fields
    fields_dir = os.path.join(os.path.dirname(__file__), 'fields')
    
    # Initialize result structure
    result = {
        "countries": [],
        "sectors": [],
        "industries": {},
        "kpis": {},
        "companies": [],
        "benchmarks": []
    }
    
    # Read countries from CSV
    try:
        countries_path = os.path.join(fields_dir, 'countries.csv')
        if os.path.exists(countries_path):
            countries_df = pd.read_csv(countries_path, dtype=str, keep_default_na=False, na_filter=False )
            result["countries"] = [
                {"country_code": row["country_code"], "country_name": row["country_name"]}
                for _, row in countries_df.iterrows()
            ]
    except Exception as e:
        print(f"Warning: Could not read countries.csv: {e}")
    
    # Read sectors from CSV
    try:
        sectors_path = os.path.join(fields_dir, 'sectors.csv')
        if os.path.exists(sectors_path):
            sectors_df = pd.read_csv(sectors_path, dtype=str, keep_default_na=False, na_filter=False)
            result["sectors"] = sectors_df["sector"].tolist()
    except Exception as e:
        print(f"Warning: Could not read sectors.csv: {e}")
    
    # Read industries from CSV
    try:
        industries_path = os.path.join(fields_dir, 'industries.csv')
        if os.path.exists(industries_path):
            industries_df = pd.read_csv(industries_path, dtype=str, keep_default_na=False, na_filter=False)
            for _, row in industries_df.iterrows():
                sector = row["sector"]
                industry = row["industry"]
                if sector not in result["industries"]:
                    result["industries"][sector] = []
                result["industries"][sector].append(industry)
    except Exception as e:
        print(f"Warning: Could not read industries.csv: {e}")
    
    # Read KPIs from CSV
    try:
        kpis_path = os.path.join(fields_dir, 'kpis.csv')
        if os.path.exists(kpis_path):
            kpis_df = pd.read_csv(kpis_path, dtype=str, keep_default_na=False, na_filter=False)

            # Vectorized build of kpi_labels mapping (kpi_name -> kpi_name_clean) if available
            if 'kpi_name_clean' in kpis_df.columns:
                labels_df = kpis_df[["kpi_name", "kpi_name_clean"]].drop_duplicates().copy()
                labels_df["kpi_name"] = labels_df["kpi_name"].astype(str).str.strip()
                labels_df["kpi_name_clean"] = labels_df["kpi_name_clean"].astype(str).str.strip()
                labels_df = labels_df[(labels_df["kpi_name"] != "") & (labels_df["kpi_name_clean"] != "")]
                result["kpi_labels"] = dict(zip(labels_df["kpi_name"], labels_df["kpi_name_clean"]))

            # Vectorized build of kpis mapping (kpi_name -> list[kpi_value])
            kv_df = kpis_df[["kpi_name", "kpi_value"]].copy()
            kv_df["kpi_name"] = kv_df["kpi_name"].astype(str).str.strip()
            kv_df["kpi_value"] = kv_df["kpi_value"].astype(str).str.strip()
            kv_df = kv_df[(kv_df["kpi_name"] != "") & (kv_df["kpi_value"] != "")]
            result["kpis"] = kv_df.groupby("kpi_name")["kpi_value"].apply(list).to_dict()
    except Exception as e:
        print(f"Warning: Could not read kpis.csv: {e}")
    
    # Read companies from CSV
    try:
        companies_path = os.path.join(fields_dir, 'companies.csv')
        if os.path.exists(companies_path):
            companies_df = pd.read_csv(companies_path, dtype=str, keep_default_na=False, na_filter=False)
            result["companies"] = [
                {"company_name": row["company_name"], "symbol": row["symbol"]}
                for _, row in companies_df.iterrows()
            ]
    except Exception as e:
        print(f"Warning: Could not read companies.csv: {e}")
    
    # Read benchmarks from CSV
    try:
        benchmarks_path = os.path.join(fields_dir, 'benchmarks.csv')
        if os.path.exists(benchmarks_path):
            benchmarks_df = pd.read_csv(benchmarks_path, dtype=str, keep_default_na=False, na_filter=False)
            result["benchmarks"] = [
                {"name": row["name"], "symbol": row["symbol"], "type": row["type"], "date": row["date"]}
                for _, row in benchmarks_df.iterrows()
            ]
    except Exception as e:
        print(f"Warning: Could not read benchmarks.csv: {e}")
    
    return result
